jobs:

  - job: macOS

    pool:
      vmImage: 'macOS-10.13'

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g yarn vsce
      displayName: Install vsce and yarn

    - script: |
        yarn
      displayName: Install node dependencies

    - script: |
        vsce package
      displayName: Package extension

    - script: |
        cp *.vsix ${BUILD_ARTIFACTSTAGINGDIRECTORY}
      displayName: Stage pacakged extension

    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'drop'
        targetPath: $(Build.ArtifactStagingDirectory)
      displayName: Publish artifacts

    - script: |
        vsce publish -p $(PERSONAL_ACCESS_TOKEN)
      displayName: Publish extension
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))

